### ISSUE TITLE
Identifying source and targets

### ISSUE THREAD

**Issue by sharma-n** [snowood1/Zero-Shot-PLOVER#1]
Hi there! Interesting work! Can I check with you on how you went about identifying the source and targets (marked by the \<S>, \<T> tags in the training/eval datasets?

**Comment by snowood1** [comment]
Hello! 
I appreciate your interest in our work! We use existing datasets from prior research with manually labeled entities . This streamlined our focus on  classifying the event types within known <S\> and <T\> pairs.  

Extracting <S\> and <T\> itself is not hard using tools like spaCy or supervided models. But evaluation multiple pairs can be complex and extend beyond our paper's scope. 

For in-depth information, please refer to Section 4.1 in our paper.
